#!/usr/bin/env zsh

xzcompilehomedir() {
    targets=(
        $HOME/.zshrc
        $HOME/.zshenv
        $HOME/.env.load
        $HOME/.aliasrc
        $HOME/.zsh
    )
    for i in $targets
    do
        [[ -d "$i" ]] && xzcompiledir $i
        [[ -f "$i" ]] && xzcompile $i
    done
    unset i
    unset targets
}
